apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: ${{ values.name }}
  namespace: crossplane-system
spec:
  forProvider:
    location: US
  providerConfigRef:
    kind: ProviderConfig
    name: default
# ---

# apiVersion: compute.gcp.m.upbound.io/v1beta1
# kind: Instance
# metadata:
#   name: ${{ values.name }}
# spec:
#   forProvider:
#     machineType: e2-medium
#     zone: us-central1-a
#     disks:
#       - autoDelete: true
#         boot: true
#         initializeParams:
#           sourceImage: projects/debian-cloud/global/images/family/debian-10
#     networkInterfaces:
#       - network: default
#   providerConfigRef:
#     name: default