apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   
spec:
  project: default
  source:
    repoURL: https://github.com/marcelo-luizz/gitops-app-infra
    targetRevision: HEAD
    path: environments/dev
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: dev-infra-automation
#   namespace: argocd
# spec:
#   generators:
#     - git:
#         repoURL: https://github.com/marcelo-luizz/gitops-app-infra
#         revision: HEAD
#         directories:
#           - path: environments/dev/* # Ele vai criar um App para cada pasta aqui
#   template:
#     metadata:
#       name: 'dev-{{path.basename}}'
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/marcelo-luizz/gitops-app-infra
#         targetRevision: HEAD
#         path: '{{path}}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: crossplane-system
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true