# =============================================================================
# ApplicationSet: app-resources-by-category
# Gera 1 Application por CATEGORIA DE RECURSO (compute-engine, pubsub, etc)
# por REGION por ENVIRONMENT
# Ex: app-homolog-southamerica-east1-compute-engine, 
#     app-homolog-southamerica-east1-pubsub, etc.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-resources-by-category
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/marcelo-luizz/gitops-app-infra.git"
        revision: HEAD
        directories:
          - path: "environments/*/*/*/*"
  template:
    metadata:
      name: "app-{{index .path.segments 3}}-{{index .path.segments 2}}-{{index .path.segments 1}}-{{index .path.segments 0}}"
      namespace: argocd
      labels:
        repo: app-infra
        resource-type: "{{index .path.segments 0}}"
        region: "{{index .path.segments 1}}"
        environment: "{{index .path.segments 2}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: "https://github.com/marcelo-luizz/gitops-app-infra.git"
        targetRevision: HEAD
        path: "{{.path.path}}"
        directory:
          recurse: true
          include: "*.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: crossplane-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
